name: flypee
description: "Fly Pee Game"
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '3.16.8'

dependencies:
  flutter:
    sdk: flutter
  flame: 1.14.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/